### ISSUE TITLE
IDGenerator fails with History Objects

### ISSUE THREAD

**Issue by itsmebasti** [apex-enterprise-patterns/fflib-apex-common#155] opened 2017-03-07 17:00 UTC
`fflib_IDGenerator.generate(CaseHistory.SObjectType)`
results in :

> System.StringException: Invalid id: null000000000001
Class.UP2GO_2T.fflib_IDGenerator.generate: line 41, column 1

Same for Custom__History objects.

**Comment by afawcett** [comment] 2017-03-08 23:30
Bah.... not really sure what we can do about this tbh, feels like a platform issue. @capeterson any thoughts?

**Comment by cropredyHelix** [comment] 2019-02-12 01:22
the bigger issue is that xxxHistory objects can't be mocked, even using json.deserialize technique

**Comment by daveespo** [comment] 2023-06-08 14:44
This is a duplicate of an issue over in the Mocks repo so I'm closing this one since it doesn't belong here

https://github.com/apex-enterprise-patterns/fflib-apex-mocks/issues/75

**Closed by daveespo** 2023-06-08 14:44 UTC
Labels: bug
